### ISSUE TITLE
Remove usage of unsafe lifecycle hooks (React 16.3)

### ISSUE THREAD

**Issue by voodee** [formsy/formsy-react#105]
Using Formsy with React 16.3 with the [<React.StrictMode></React.StrictMode>](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#strictmode-component) component will trigger some warnings.

**Comment by rkuykendall** [comment]
This has been fixed in the new 2.0.0 release. Thank you for your patience! :tada: 

Please re-open this ticket or create a new one if I am mistaken.

# v2.0.0

- Much, much faster
- Many, many bug fixes
- Full Typescript typing
- Fixed deprecated lifecycle methods 
- Updated all libraries
- Fixed a number of legacy decisions in the Formsy API, mostly a reliance on function props over value props passed down to wrapped components. However, the API changes are minor and listed below:
  - `getErrorMessage()` => `errorMessage`
  - `getErrorMessages()` => `errorMessages`
  - `getValue()` => `value`
   `hasValue()` => `hasValue`
  - `isFormDisabled():` => `isFormDisabled`
  - `isFormSubmitted()` => `isFormSubmitted`
  - `isPristine()` => `isPristine`
  - `isRequired()` => `isRequired`
  - `isValid():` => `isValid`
  - `showError()` => `showError`
  - `showRequired()` => `showRequired`

https://github.com/formsy/formsy-react/compare/v1.1.4...v2.0.0
