### ISSUE TITLE
Validation error displaying even when value is correct

### ISSUE THREAD

**Issue by ihd2911** [formsy/formsy-react#106]
I have added following in component.
On load i am passing value to since, even when value is correct, still it shows error and disable my form. once i delete last character and re-enter value it starts working

TextFieldFormsy is my high level component

```
<TextFieldFormsy
       className="mb-16"
       type="number"
       name="since"
       label="Since"
       value={since}
       validations="isLength:4"
       validationErrors={{
           isLength: 'Please enter 4 digits e.g 2018'
       }}
/>
```

**Comment by MilosRasic** [comment]
Can you please share your implementation of TextFieldFormsy?

**Comment by MilosRasic** [comment]
Works perfectly for me with 1.1.4.

The only possible difference could be versions or the `since` variable. I set it to `'2018'` in the parent component's render. Is this similar to how you use it?

Other than that I have no idea where else to look. Maybe a jsbin/codepen//codesandbox/something else example would help.

**Comment by ihd2911** [comment]
Strange, I will try again
