### ISSUE TITLE
Make a Form with render prop

### ISSUE THREAD

**Issue by jaimesangcap** [formsy/formsy-react#108]
This is just an idea, I'm not sure if it's currently possible 😄 

Expose a `<Formsy/>` component as render prop.

```
<Formsy>
  {({ Input }) => {
    <Input name="myInput" display={props => <MyCustomInput  {...props} />}/>
  }}
</Formsy>
```

With this, we can avoid using the `withFormsy` HOF in separate location.

I want to work on this feature if it is feasible.

**Comment by MilosRasic** [comment]
I'm quite unsure about this to be honest. I've considered a less verbose HOC API in the past but it didn't gain much traction: #77 

Please check it out and let us know what you think.

Ideally I'd like to see a simple API that still supports full customization, implemented as whatever is best of this case, free from hype about render props that still seems to be going on in the community. Multiple APIs, both HOCs and render props, would also be fine as long as they use the same underlaying patterns to connect the field to the form.

I've also started a rewrite of form state in state-refactoring branch which is branched off v2.0. Might be good to wait for this to be completed so that we don't have horrible merge conflicts.

**Comment by jaimesangcap** [comment]
I understand your point about render props. As someone who slowly transitioning to frontend dev, you might got carried away with a lot of things that happening 😄 Probably as relatively new to react, this might be the available pattern/info I have as of the moment.

For now I think I can try to help with the state-refactoring and see how things will go.

**Comment by rkuykendall** [comment]
Closing this as it's not something anyone is currently promoting or working on, and I want to keep the tickets clean. If anyone is interested in continuing this ticket please re-open!
