### ISSUE TITLE
Set initial values of form

### ISSUE THREAD

**Issue by yirenWang** [formsy/formsy-react#111]
"It would be nice if I could simply inject all the values at once using a value or values prop on the parent form" https://github.com/christianalfoni/formsy-react/issues/183 

I would like to do that but I don't see this functionality documented anywhere. How would I go about doing it ? Setting values as a prop on Formsy doesn't do anything. 

Thanks !

**Comment by MilosRasic** [comment]
#64

**Comment by yirenWang** [comment]
Thanks ! I really need to level up my googling skills ^^

**Comment by MilosRasic** [comment]
Or github issue searching skills. Make sure to remove is:open from the search so that you search the closed issues as well. :)

**Comment by rkuykendall** [comment]
This has been fixed in the new 2.0.0 release. The new added function is `formsy.updateInputsWithValue` and it works very similarly to `updateInputsWithError`.

Please re-open this ticket or create a new one if I am mistaken.

# v2.0.0

- Much, much faster
- Many, many bug fixes
- Full Typescript typing
- Fixed deprecated lifecycle methods 
- Updated all libraries
- Fixed a number of legacy decisions in the Formsy API, mostly a reliance on function props over value props passed down to wrapped components. However, the API changes are minor and listed below:
  - `getErrorMessage()` => `errorMessage`
  - `getErrorMessages()` => `errorMessages`
  - `getValue()` => `value`
   `hasValue()` => `hasValue`
  - `isFormDisabled():` => `isFormDisabled`
  - `isFormSubmitted()` => `isFormSubmitted`
  - `isPristine()` => `isPristine`
  - `isRequired()` => `isRequired`
  - `isValid():` => `isValid`
  - `showError()` => `showError`
  - `showRequired()` => `showRequired`

https://github.com/formsy/formsy-react/compare/v1.1.4...v2.0.0
