### ISSUE TITLE
Unnecessary calls to validateForm kills performance

### ISSUE THREAD

**Issue by larshelg** [formsy/formsy-react#113]
When a form is attached/mounted or detached/unmounted formsy calls validateForm not one time but many times for each component. This can be seen by debugging into the attachToForm or detachFromForm methods in main.js. 

This gives terrible performance when navigating from one big form to another. ValidateForm is then called first for every input component in the form you're navigating from and then for every component you're navigating to. For really big forms in Internet Explorer the app just freezes up with "long execution script error". 

It would seem that it should be sufficient to do this only one time in componentDidMount and componentWillUnmount. 
And maybe even consider a prop for those who dont need a initial validating when a form mounts/unmounts.

Monkeypatching like this solves the problem: 

```
Formsy.prototype.detachFromForm = function (component){
  const componentPos = this.inputs.indexOf(component);
  if (componentPos !== -1) {
    this.inputs = this.inputs.slice(0, componentPos).concat(this.inputs.slice(componentPos + 1));
  }
  NB!!! validateForm is commented out
   //this.validateForm();
};
```

**Comment by MilosRasic** [comment]
A good hack for your case, or at least as good as a hack can be.

We have to call validateForm when a field detaches from form however, because unmounting the form isn't the only case when detaching happens. It can also happen when a field in the form is being conditionally rendered, and validation has to be ran because validations of other fields may depend on the value of the field being unmounted.

Will try to fix this in state-refactoring branch, but open source time is scarce these days :(

**Comment by larshelg** [comment]
Thanks for the feedback.

I guess this hack would be safe for apps that dont have input fields that depend on  the validation on other fields. 

Yeah, being able to set this as part of state/prop would be great.
