### ISSUE TITLE
Add prettier for code conventions

### ISSUE THREAD

**Issue by apuntovanini** [formsy/formsy-react#12]
I think adding prettier may fix some different coding styles preferences

**Comment by rkuykendall** [comment]
I noticed the project is already inheriting the airbnb eslint as of 1.0. That should standardize everything, right? What exactly did you have in mind?

**Comment by rkuykendall** [comment]
Hm, It doesn't look like eslint is running in travis though, so we may be unaware of those standards.

**Comment by MilosRasic** [comment]
I too prefer prettier but maybe we shouldn't change what's already in place and working.

**Comment by apuntovanini** [comment]
They are different though: airbnb coding styles are not the same of prettier so far, there's a lot of discussion going on about it. Prettier makes being consistent easier, since it can be automated with pre-commit hooks. It's not a priority though, we can add a label as a reminder for future versions
Formsy codebase is not big anyways, so it won't change a lot of things

**Comment by rkuykendall** [comment]
I've been hearing more and more about the benefits of prettier.

**Comment by zabute** [comment]
I think [prettier-eslint](https://github.com/prettier/prettier-eslint) will be better for this project. It will respect the eslint config so no drastic changes will come to the code style.

I suppose the only benefit here would be that it would improve the contributing experience. If I remember correctly, I had to push another commit because I forgot to lint before submitting a PR. A pre-commit hook that ran ```prettier-eslint```on the entire codebase would have prevented that.
