### ISSUE TITLE
react > 16 deprecated lifecycles

### ISSUE THREAD

**Issue by gitbejbe1** [formsy/formsy-react#319]
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Formsy(TextFieldFormsy)

**Comment by rkuykendall** [comment]
This has been fixed in the 2.x beta releases, which should be released in the coming week / weeks. :)

**Comment by toreyhickman** [comment]
I'm experiencing the same issue after updating React.  Is there any update on the expected release date?  

I'm debating using the beta version in the meantime.

**Comment by rkuykendall** [comment]
You should, the beta is very complete. The release is waiting on a types commit, I just asked for an estimate here: https://github.com/formsy/formsy-react/issues/10#issuecomment-577848351

**Comment by toreyhickman** [comment]
We've updated to the beta version.  It's working well!  Thank you.

**Comment by rkuykendall** [comment]
This has been fixed in the new 2.0.0 release. Thank you all for your patience! :tada: 

Please re-open this ticket or create a new one if I am mistaken.

# v2.0.0

- Much, much faster
- Many, many bug fixes
- Full Typescript typing
- Fixed deprecated lifecycle methods 
- Updated all libraries
- Fixed a number of legacy decisions in the Formsy API, mostly a reliance on function props over value props passed down to wrapped components. However, the API changes are minor and listed below:
  - `getErrorMessage()` => `errorMessage`
  - `getErrorMessages()` => `errorMessages`
  - `getValue()` => `value`
   `hasValue()` => `hasValue`
  - `isFormDisabled():` => `isFormDisabled`
  - `isFormSubmitted()` => `isFormSubmitted`
  - `isPristine()` => `isPristine`
  - `isRequired()` => `isRequired`
  - `isValid():` => `isValid`
  - `showError()` => `showError`
  - `showRequired()` => `showRequired`

https://github.com/formsy/formsy-react/compare/v1.1.4...v2.0.0
