### ISSUE TITLE
Entire form validated when a form element is added or removed

### ISSUE THREAD

**Issue by batr94** [formsy/formsy-react#53]
The problem is still exist.
https://github.com/christianalfoni/formsy-react/issues/431

**Comment by MilosRasic** [comment]
The issue here is that we have to support the use case where validation depends on multiple fields (confirm password for example) or validation of one field depends on contents of other fields (for example text input is required only if a certain combination of checkboxes is checked).

There's no easy way out, but we might want to add a flag to indicate the form is "pure", meaning no complex validations that depend on multiple fields, and validate only the field that changed when it is set.

Other thing you might want to look at is optimising your form fields. Each of them will be rerendering every time anything in the form change, so for the more complex ones it might make sense to implement a SCU and/or memoize any calculations you may be doing in render().

**Comment by rkuykendall** [comment]
Since this is a performance issue we know about, which would require new features to improve, I'm going to say it's an enhancement not a bug. Does that sound good, @batr94?

**Comment by batr94** [comment]
Ok, it sounds good. Thank you for explanation.
