### ISSUE TITLE
What is the correct way of changing input value from outside input?

### ISSUE THREAD

**Issue by eranshabi** [formsy/formsy-react#54]
Hello,
I want to change one of my inputs value after another input value was changed.
What is the correct way of doing so?
Right now I do this on the component that has the `<Formsy>`:
```js
onFormChange(currentValues) {
        currentValues.inputIWantToChange = newValue;
}

<Formsy onChange={this.onFormChange.bind(this)} ref="form">
```

but I'm not sure this was the intended way, and also It doesn't work for me in tests (using enzyme/jsdom), but only on real browser.
Is there another way?

Thanks

**Comment by rkuykendall** [comment]
That seems like a valid way to me. Formsy isn't actually very opinionated at how **exactly** you do things. It's more of a set of tools. Another option would be passing on `onChange` prop to your Formsy component.

> It doesn't work for me in tests (using enzyme/jsdom), but only on real browser

Try, after you change the element, triggering a blur event.

**Comment by MilosRasic** [comment]
I can't figure out why exactly this is working. currentValues comes from component states, so if it's working, you seem to be mutating component state which is never a good idea.

My top option here would be keeping the value of the dependent component in the form's parent component state and changing it in your onFormChange(). Something like:

```
onFormChange(currentValues) {
        this.setState({
                dependentValue: newValue,
        })
}
```

and then

```
<Formsy>
        <DependentField value={this.state.dependentValue} />
</Formsy>
```

The other way less hacky than mutating state would be the setValue() method on a form field component which should be provided by withFormsy HOC. You'd have to put a ref on the field, then:

```
onFormChange(currentValues) {
        this.refs.dependentField.setValue(newValue);
}
```

This will call the field component's setState rather than mutating state.

Not sure about the enzyme part... I'm struggling with the thing myself too, but if you're trying simulate() and it's not working, you could always call the handler directly on the component instance. It should be the same thing.

**Comment by eranshabi** [comment]
Thank you all. I used @MilosRasic second suggestion. Is there a way to know what fields exactly changed inside `onChange(currentValues, isChanged)`?
