### ISSUE TITLE
dependabot?

### ISSUE THREAD

**Issue by MilosRasic** [formsy/formsy-react#73]
Is this really a good idea? Might be for some other languages, but for javascript with npm, well, let me explain the issue.

By default, caret deps are used in package.json. When installing a dep, npm will process a caret dep by installing the latest version with the same minor number in case of versions below 1.0.0, or with the same major number when versions are at or above 1.0.0.

This means minor version bump will not only change nothing, but even worse, if we update package.json we are saying our package is no longer compatible with earlier versions of its deps, which is simply false and may also cause issues for dependant projects which are for some reason forced to use a common dep at fixed version (no caret).

Is it possible to set up dependabot to check only new versions that wouldn't be picked up by caret deps? If not, I'd be in favour of turning it off.

**Comment by rkuykendall** [comment]
That's a really good point. This project actually seems to be pretty low development speed now that most everyone's big issues are taken care of. And we really don't need the absolute latest eslint or whatever.

My PR for value-props needs work in documentation/testing but nobody seems to care all that much ( myself included ). @th3fallen's onChange PR is important and we really should get it out, but requires at least a somewhat major release for a breaking change like that. But after that, I could see this project going into a lower-key mode for a while.

**Comment by th3fallen** [comment]
anything i can lend a hand on to speed things up?

**Comment by rkuykendall** [comment]
@th3fallen Yeah sorry for the delay. Wish we had gotten it in for v1, less of an awkward time for breaking changes. The change is good. It's larger than a minor version bump, but smaller than a 2.x.x one. I just read over the documentation and none of it would need to change. Your PR actually makes it more in line with what a reader would expect.

How do you feel about rebasing it and adding a version bump to 1.2.0 in `package.json`, adding a big BREAKING thing in the changelog explaining the change, rebasing and building? I think it's safe to say we don't have a big 2.x.x coming up so that's the safest way I see to get it out.

What do you think @MilosRasic?

**Comment by th3fallen** [comment]
i think that sounds reasonable.

**Comment by MilosRasic** [comment]
Honestly, both PRs seem too breaking for even a minor version bump, but yeah, formsy is pretty complete and we don't have much material for a 2.0.0 without a major rework, so let's do 1.2.0.

I'd really like to do some performance testing regarding my comment on #48. If I find any issues and we manage to fix them we can always do a 1.2.1 for that.

**Comment by MilosRasic** [comment]
Actually, I gave this more thought and I don't think we can make this a 1.2 without breaking semver completely. Both are completely api-breaking changes and should require a major release.

What do you guys think about starting a 2.0 branch and publishing a beta with those two changes? In the meantime we could also release a 1.2 with #50 but with support for methods retained and deprecated.

**Comment by rkuykendall** [comment]
I was going to just drop https://github.com/formsy/formsy-react/pull/50 for now, not include it in 1.2.0. I see https://github.com/formsy/formsy-react/pull/48 as less of a big deal, since the change is actually what someone would expect to come from onChange if you just read the documentation. It's true though that it will break some existing codebases, which is not backwards compatible, so I do see your concern.

**Comment by rkuykendall** [comment]
The thing with doing https://github.com/formsy/formsy-react/pull/50 in a way that is backwards compatible is coming up with sane names. What should the new `hasValue` be?

**Comment by MilosRasic** [comment]
Inactive and slightly derailed. Hopefully we've agreed that 2.0.0 is the best solution, we just need some time to set up a @next release. Closing.
